### ISSUE TITLE
Feature request. X button should be in appropriate to the app a style 

### ISSUE THREAD

**Issue by Mariahma** [fadich/nphoto#23]
**WTR:**
**1.** Open the app
**2.** Open any photo
**3.** Pay attention on the X button in the right corner

**Actual result:**
Now close button is blue and unpretty. It doesn't look in the appropriate style.
**Expected result:**
The shape and color of X button should be more appropriate to the style of a whole app (ex: white color, more transparent and be highlighted when hovering). X button from facebook can be used as referance.

**Comment by fadich** [comment]
Close button has been changed and made white.

**Comment by Mariahma** [comment]
Checked. Fixed!
